site_name: Victoriee Tech Journal

theme:
  name: material
  # Logos use docs/ folder as root
  logo: V-icon-512x512.png
  favicon: V-favicon-32x32.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.top

plugins:
  - search
  - awesome-pages #Docs: https://henrywhitaker3.github.io/mkdocs-material-dark-theme/plugins/awesome-pages/
  - blog:
      blog_toc: true
      pagination: true
  - mermaid2
  - privacy:
      enabled: !ENV [CI, false] #Docs: https://squidfunk.github.io/mkdocs-material/plugins/privacy/
  - git-revision-date-localized:
          enable_creation_date: true
          type: iso_date

markdown_extensions:
  - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/solid/book
      link: / # This site
    - icon: fontawesome/solid/blog
      link: /blog/
    - icon: fontawesome/brands/github
      link: https://github.com/VictorieeMan
    - icon: fontawesome/brands/medium
      link: https://medium.com/@VictorieeMan
    - icon: fontawesome/solid/gift
      link: https://victoriee.com/donate
    - icon: fontawesome/brands/bitcoin
      link: https://victoriee.com/btcpay
    - icon: fontawesome/brands/ethereum
      link: https://victoriee.eth.xyz/
    - icon: fontawesome/solid/phone
      link: https://vida.page/victorieeman
    - icon: fontawesome/solid/envelope
      link: mailto:gh-pages.s8o1g@e-mail.victoriee.org

exclude_docs: |
  blog/readme.md