site_name: VictorieeMan Tech Journal & Blog

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
  - navigation.tabs
  - navigation.top

nav:
  - blog/index.md

plugins:
  - blog
  - mermaid2
  - git-revision-date-localized:
          enable_creation_date: true
          type: iso_date

markdown_extensions:
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/solid/book
      link: /
    - icon: fontawesome/solid/blog
      link: /blog/ # This site
    - icon: fontawesome/brands/github
      link: https://github.com/VictorieeMan
    - icon: fontawesome/brands/medium
      link: https://medium.com/@VictorieeMan
    - icon: fontawesome/solid/gift
      link: https://victoriee.com/donate
    - icon: fontawesome/brands/bitcoin
      link: https://victoriee.com/btcpay
    - icon: fontawesome/brands/ethereum
      link: https://victoriee.eth.xyz/
    - icon: fontawesome/solid/phone
      link: https://vida.page/victorieeman
    - icon: fontawesome/solid/envelope
      link: mailto:gh-pages.s8o1g@e-mail.victoriee.org