name: Build and Deploy
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg

      # Prepare directories
      - name: Prepare Directories
        run: |
          mkdir -p gh-pages/docs
          mkdir -p gh-pages/blog

      # Build the docs site
      - name: Build Docs Site
        run: |
          cd docs-site
          mkdocs build --site-dir ../gh-pages/docs

      # Build the blog site
      - name: Build Blog Site
        run: |
          cd blog-site
          mkdocs build --site-dir ../gh-pages/blog

      # Check the contents of the directories
      - name: Check Directory Contents
        run: |
          echo "Contents of gh-pages/docs:"
          ls -l gh-pages/docs
          echo "Contents of gh-pages/blog:"
          ls -l gh-pages/blog

      # Deploy to GitHub Pages
      - run: |
          cd gh-pages
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages