name: Build and Deploy
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg

      # Build and deploy the docs site
      - name: Build and Deploy Docs Site
        run: |
          cd docs-site
          mkdocs build
          # Copy the built docs-site to the root directory in a subdirectory named docs
          mkdir -p ../docs
          cp -r site/* ../docs

      # Build and deploy the blog site
      - name: Build and Deploy Blog Site
        run: |
          cd blog-site
          mkdocs build
          # Copy the built blog-site to the root directory in a subdirectory named blog
          mkdir -p ../blog
          cp -r site/* ../blog

      # Commit and push the changes to the gh-pages branch
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force