name: Build and Deploy
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg

      # Build the docs site
      - name: Build Docs Site
        run: |
          cd docs-site
          mkdocs build
          # Copy the built docs-site to a subdirectory named docs
          mkdir -p ../gh-pages/docs
          cp -r site/* ../gh-pages/docs

      # Build the blog site
      - name: Build Blog Site
        run: |
          cd blog-site
          mkdocs build
          # Copy the built blog-site to a subdirectory named blog
          mkdir -p ../gh-pages/blog
          cp -r site/* ../gh-pages/blog

      # Deploy to GitHub Pages
      - run: |
          cd ../gh-pages
          git init
          git remote add origin https://${{ secrets.GITHUB_TOKEN }}@github.com/VictorieeMan/VictorieeMan.github.io.git
          git checkout -b gh-pages
          git add .
          git commit -m "Update GitHub Pages"
          git push -u origin gh-pages --force